### ISSUE TITLE
Will there be paper-implementations?

### ISSUE THREAD

**Issue by kadirnar** [simurgailab/an-enhanced-tooth-segmentation-in-bitewing-radiographs#1]
Will you share the code of the article?

**Comment by dilaraozdemir** [comment]
Since it is an ongoing project and a health project, the author does not plan to share the source codes directly, considering that it may cause ethical problems. However, in the future, the Mask R-CNN implementation on the custom dataset will be shared under the organization page.

**Comment by buseyaren** [comment]
**Hello, it does not seem possible for me to share the first code draft of the work as my teammate said. However, this master thesis, which I have discussed at length in my work, seems to be very useful;**
http://acikerisim.karabuk.edu.tr:8080/xmlui/bitstream/handle/123456789/1508/10423328.pdf?sequence=1&isAllowed=y

**Furthermore, this video, for which I gave an example of custom multi-class segmentation, can be considered a similar source of this work;**
https://www.youtube.com/watch?v=Ldnmxa4pM3g&t=1501s
