### ISSUE TITLE
Dataset Access...

### ISSUE THREAD

**Issue by AISoltani** [simurgailab/an-enhanced-tooth-segmentation-in-bitewing-radiographs#2]
@buseyaren , @dilaraozdemir , @elifmeseci Dear My Friend.
Thank you for your great job, it was awsome!.

to use this work for Mask R-CNN, how can we access to tooth mask data? is there any dataset?

**Comment by elifmeseci** [comment]
Hello AISoltani,
Thank you for your interest in our project and for your nice comment.  Our dataset, consisting of dental images and labels, was obtained from the hospital as part of the research. However, we can only share our dataset with the condition of collaborating.
